### ISSUE TITLE
Apostrophes on Firefox triggers quick look (links)

### ISSUE THREAD

**Issue by charlesphil** [MananTank/cybertype#4]
Hey @MananTank, found a bug while trying the quotes text today (mov attached):

https://user-images.githubusercontent.com/71610407/195882262-54274732-8174-44d3-9c62-a76a175eee1e.mov

When the setting for `accessibility.typeaheadfind.manual` in Firefox's `about:config` is "true", the forward-slash (/) and apostrophe (') will trigger the [quick find and quick find (links)](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_search) functionality in Firefox. I can get around this by turning the setting to "false", but this will probably affect most Firefox users as this is the default setting.

Thanks again for the app!

**Comment by MananTank** [comment]
Hi @charlesphil, Thanks for creating this issue! 

I have fixed this issue in https://github.com/MananTank/cybertype/commit/8f305c4da979c1b8b7e41a8c1866d6d2a978ff39 

Please verify

**Comment by charlesphil** [comment]
@MananTank It works!
